// Code generated by entc, DO NOT EDIT.

package resources

import (
	"time"
)

const (
	// Label holds the string label denoting the resources type in the database.
	Label = "resources"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldIcon holds the string denoting the icon field in the database.
	FieldIcon = "icon"
	// FieldTag holds the string denoting the tag field in the database.
	FieldTag = "tag"
	// FieldDesc holds the string denoting the desc field in the database.
	FieldDesc = "desc"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldCreatedUserName holds the string denoting the created_user_name field in the database.
	FieldCreatedUserName = "created_user_name"
	// FieldUpdatedUserName holds the string denoting the updated_user_name field in the database.
	FieldUpdatedUserName = "updated_user_name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the resources in the database.
	Table = "resources"
)

// Columns holds all SQL columns for resources fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldIcon,
	FieldTag,
	FieldDesc,
	FieldURL,
	FieldCreatedUserName,
	FieldUpdatedUserName,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)
