// Code generated by "stringer -type=UserType -linecomment"; DO NOT EDIT.

package entity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserTypePublisher-1]
	_ = x[UserTypeWechat-2]
	_ = x[UserTypeLogin-3]
	_ = x[UserTypeTourist-4]
}

const _UserType_name = "publisherwechatlogintouristt"

var _UserType_index = [...]uint8{0, 9, 15, 20, 28}

func (i UserType) String() string {
	i -= 1
	if i < 0 || i >= UserType(len(_UserType_index)-1) {
		return "UserType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _UserType_name[_UserType_index[i]:_UserType_index[i+1]]
}
