// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/CuiYao631/mini_program-server-go/ent/resources"
)

// ResourcesCreate is the builder for creating a Resources entity.
type ResourcesCreate struct {
	config
	mutation *ResourcesMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (rc *ResourcesCreate) SetTitle(s string) *ResourcesCreate {
	rc.mutation.SetTitle(s)
	return rc
}

// SetIcon sets the "icon" field.
func (rc *ResourcesCreate) SetIcon(s string) *ResourcesCreate {
	rc.mutation.SetIcon(s)
	return rc
}

// SetTag sets the "tag" field.
func (rc *ResourcesCreate) SetTag(s string) *ResourcesCreate {
	rc.mutation.SetTag(s)
	return rc
}

// SetDesc sets the "desc" field.
func (rc *ResourcesCreate) SetDesc(s string) *ResourcesCreate {
	rc.mutation.SetDesc(s)
	return rc
}

// SetURL sets the "url" field.
func (rc *ResourcesCreate) SetURL(s string) *ResourcesCreate {
	rc.mutation.SetURL(s)
	return rc
}

// SetCreatedUserName sets the "created_user_name" field.
func (rc *ResourcesCreate) SetCreatedUserName(s string) *ResourcesCreate {
	rc.mutation.SetCreatedUserName(s)
	return rc
}

// SetUpdatedUserName sets the "updated_user_name" field.
func (rc *ResourcesCreate) SetUpdatedUserName(s string) *ResourcesCreate {
	rc.mutation.SetUpdatedUserName(s)
	return rc
}

// SetCreatedAt sets the "created_at" field.
func (rc *ResourcesCreate) SetCreatedAt(t time.Time) *ResourcesCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *ResourcesCreate) SetNillableCreatedAt(t *time.Time) *ResourcesCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetUpdatedAt sets the "updated_at" field.
func (rc *ResourcesCreate) SetUpdatedAt(t time.Time) *ResourcesCreate {
	rc.mutation.SetUpdatedAt(t)
	return rc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rc *ResourcesCreate) SetNillableUpdatedAt(t *time.Time) *ResourcesCreate {
	if t != nil {
		rc.SetUpdatedAt(*t)
	}
	return rc
}

// SetID sets the "id" field.
func (rc *ResourcesCreate) SetID(s string) *ResourcesCreate {
	rc.mutation.SetID(s)
	return rc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (rc *ResourcesCreate) SetNillableID(s *string) *ResourcesCreate {
	if s != nil {
		rc.SetID(*s)
	}
	return rc
}

// Mutation returns the ResourcesMutation object of the builder.
func (rc *ResourcesCreate) Mutation() *ResourcesMutation {
	return rc.mutation
}

// Save creates the Resources in the database.
func (rc *ResourcesCreate) Save(ctx context.Context) (*Resources, error) {
	var (
		err  error
		node *Resources
	)
	rc.defaults()
	if len(rc.hooks) == 0 {
		if err = rc.check(); err != nil {
			return nil, err
		}
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ResourcesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rc.check(); err != nil {
				return nil, err
			}
			rc.mutation = mutation
			if node, err = rc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			if rc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *ResourcesCreate) SaveX(ctx context.Context) *Resources {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *ResourcesCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *ResourcesCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *ResourcesCreate) defaults() {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := resources.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		v := resources.DefaultUpdatedAt()
		rc.mutation.SetUpdatedAt(v)
	}
	if _, ok := rc.mutation.ID(); !ok {
		v := resources.DefaultID()
		rc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *ResourcesCreate) check() error {
	if _, ok := rc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "title"`)}
	}
	if _, ok := rc.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`ent: missing required field "icon"`)}
	}
	if _, ok := rc.mutation.Tag(); !ok {
		return &ValidationError{Name: "tag", err: errors.New(`ent: missing required field "tag"`)}
	}
	if _, ok := rc.mutation.Desc(); !ok {
		return &ValidationError{Name: "desc", err: errors.New(`ent: missing required field "desc"`)}
	}
	if _, ok := rc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "url"`)}
	}
	if _, ok := rc.mutation.CreatedUserName(); !ok {
		return &ValidationError{Name: "created_user_name", err: errors.New(`ent: missing required field "created_user_name"`)}
	}
	if _, ok := rc.mutation.UpdatedUserName(); !ok {
		return &ValidationError{Name: "updated_user_name", err: errors.New(`ent: missing required field "updated_user_name"`)}
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "updated_at"`)}
	}
	return nil
}

func (rc *ResourcesCreate) sqlSave(ctx context.Context) (*Resources, error) {
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(string)
	}
	return _node, nil
}

func (rc *ResourcesCreate) createSpec() (*Resources, *sqlgraph.CreateSpec) {
	var (
		_node = &Resources{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: resources.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: resources.FieldID,
			},
		}
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rc.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resources.FieldTitle,
		})
		_node.Title = value
	}
	if value, ok := rc.mutation.Icon(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resources.FieldIcon,
		})
		_node.Icon = value
	}
	if value, ok := rc.mutation.Tag(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resources.FieldTag,
		})
		_node.Tag = value
	}
	if value, ok := rc.mutation.Desc(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resources.FieldDesc,
		})
		_node.Desc = value
	}
	if value, ok := rc.mutation.URL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resources.FieldURL,
		})
		_node.URL = value
	}
	if value, ok := rc.mutation.CreatedUserName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resources.FieldCreatedUserName,
		})
		_node.CreatedUserName = value
	}
	if value, ok := rc.mutation.UpdatedUserName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: resources.FieldUpdatedUserName,
		})
		_node.UpdatedUserName = value
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: resources.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: resources.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ResourcesCreateBulk is the builder for creating many Resources entities in bulk.
type ResourcesCreateBulk struct {
	config
	builders []*ResourcesCreate
}

// Save creates the Resources entities in the database.
func (rcb *ResourcesCreateBulk) Save(ctx context.Context) ([]*Resources, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Resources, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourcesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *ResourcesCreateBulk) SaveX(ctx context.Context) []*Resources {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *ResourcesCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *ResourcesCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
