// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "联系人",
            "url": "联系网址",
            "email": "联系人邮箱"
        },
        "license": {
            "name": "(Apache 2.0)"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/delete": {
            "post": {
                "description": "删除壁纸",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DeleteWallpaper"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "解析请求body错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "请求路径错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/get": {
            "post": {
                "description": "获取单个壁纸",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetWallpaper"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "仓库名",
                        "name": "bucketName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件名",
                        "name": "fileName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "解析请求body错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "请求路径错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/wallpaper/list": {
            "post": {
                "description": "壁纸列表",
                "tags": [
                    "ListWallpaper"
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "解析请求body错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "请求路径错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/wallpaper/upload": {
            "post": {
                "description": "上传壁纸",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UploadWallpaper"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "仓库名",
                        "name": "bucketName",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件路径",
                        "name": "file",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "解析请求body错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "请求路径错误",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "版本号:(v1.0)",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "标题",
	Description:      "描述",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
