// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Resources is the predicate function for resources builders.
type Resources func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
